// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineCoursePlatform.API.Infrastructure.Data;

#nullable disable

namespace OnlineCoursePlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("OnlineCoursePlatform.API.Core.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a51bf05c-b378-4c5e-a610-b41cffc997a8"),
                            Description = "Learn React from scratch to advanced topics.",
                            InstructorId = new Guid("21943b33-2adf-428c-89f8-4d0a9c46c006"),
                            Price = 49.99m,
                            Title = "Mastering React"
                        });
                });

            modelBuilder.Entity("OnlineCoursePlatform.API.Core.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("OnlineCoursePlatform.API.Core.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1285742a-9683-41bd-a2b4-5fb20d183322"),
                            CourseId = new Guid("a51bf05c-b378-4c5e-a610-b41cffc997a8"),
                            Order = 1,
                            Title = "Introduction to React",
                            VideoUrl = "https://example.com/video1.mp4"
                        },
                        new
                        {
                            Id = new Guid("96212196-b64a-469c-9f10-cebdac8f8dba"),
                            CourseId = new Guid("a51bf05c-b378-4c5e-a610-b41cffc997a8"),
                            Order = 2,
                            Title = "State and Props",
                            VideoUrl = "https://example.com/video2.mp4"
                        });
                });

            modelBuilder.Entity("OnlineCoursePlatform.API.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8fb3fcff-9a95-435b-90f5-3cb5e98dab6b"),
                            Email = "admin@example.com",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$L5Z9Jm4hhR/rIpA6DFzKFu9bE9Ri34CQJZu7aY31vUBKNOpEvMwF.",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("21943b33-2adf-428c-89f8-4d0a9c46c006"),
                            Email = "instructor@example.com",
                            Name = "Instructor John",
                            PasswordHash = "$2a$11$cyAHQIfpbjZsnH/Cd81EW.hi8DNCAoE2s5cslciIj.yPe75brKKzK",
                            Role = "Instructor"
                        },
                        new
                        {
                            Id = new Guid("2a405d57-ea1f-4809-a8af-296d58370923"),
                            Email = "student@example.com",
                            Name = "Student Jane",
                            PasswordHash = "$2a$11$Q3YhxJllRFbuiHlodj.9kuW1nA729Y5TJXUXzJm6KDVpyzf6sey4m",
                            Role = "Student"
                        });
                });

            modelBuilder.Entity("OnlineCoursePlatform.API.Core.Entities.Course", b =>
                {
                    b.HasOne("OnlineCoursePlatform.API.Core.Entities.User", "Instructor")
                        .WithMany("AuthoredCourses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("OnlineCoursePlatform.API.Core.Entities.Enrollment", b =>
                {
                    b.HasOne("OnlineCoursePlatform.API.Core.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineCoursePlatform.API.Core.Entities.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineCoursePlatform.API.Core.Entities.Lesson", b =>
                {
                    b.HasOne("OnlineCoursePlatform.API.Core.Entities.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("OnlineCoursePlatform.API.Core.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("OnlineCoursePlatform.API.Core.Entities.User", b =>
                {
                    b.Navigation("AuthoredCourses");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
